### ISSUE TITLE
Where are my diamonds? D:

### ISSUE THREAD

**Issue by MelanX** [strifel/Mod_WoodenFurnace#1]
https://imgur.com/a/twXJE6W

Fix it please :c

**Comment by strifel** [comment]
This was actually planned, but maybe I will "fix" it.

**Comment by strifel** [comment]
Fixed by d94627ad53d76130e925ecf36aa72d52ab2a8812
And yes I know that you can still place the furnace and then set blocks next to: THIS IS NOT AN ISSUE
