### ISSUE TITLE
Bug - Wooden furnace turns into vanilla furnace when smelting, but acts normally.

### ISSUE THREAD

**Issue by DWX12** [strifel/Mod_WoodenFurnace#5]
Great mod by the way and something that I'll be using in my pack for sure.

While testing this out I noticed the wooden furnace transformed into a vanilla furnace until it was done smelting then disappeared as intended. The furnace isn't exactly vanilla though because I'm using the Vanilla Immersion mod:

https://minecraft.curseforge.com/projects/vanilla-immersion?gameCategorySlug=mc-mods&projectID=245247

So it's actually turning into their furnace, which is replacing the vanilla furnace. It's a minor bug, but I didn't try breaking it to see if I would get the furnace or not.

Question: If a furnace is mined up while smelting, does it just get destroyed and spit out the contents?
Also, the furnace needs only accept one single item in each slot instead of multiples and stacks. The other thing that could be tweaked also is the fire radius, which could be 3x4x3 or 3x5x3 since one could just dig a 3x3 pit around the furnace to avoid the fire. It's not really a huge issue, but would make it a bit more dangerous.

Thank you again for such a cool mod.

**Comment by strifel** [comment]
Sorry. I had no time to fix it. Now it is fixed with commit 1916f1e9863809604c0e51c5f6350f3e15a4b676.
Will soon be on curseforge, too
