### ISSUE TITLE
Add config option to disable fire

### ISSUE THREAD

**Issue by friendlyhj** [strifel/Mod_WoodenFurnace#8]
Issue #1 have said it.But I think it is unreasonable.Blocks should be burned rather than deleted.

**Comment by friendlyhj** [comment]
In addition,I think there should be a config to enable/disable wooden furnace to spawn fire.A single-use and slow furnace is hardcore enough.

**Comment by strifel** [comment]
I really think it is no problem that they are replaced, because of you cant set it if there are blocks nearby.

But config option is a good idea. Will implement that

**Comment by friendlyhj** [comment]
Maybe you can add a tooltip.

**Comment by strifel** [comment]
I already thought about that, but I think you will not place anything in fire.
And because it is an single use item there should not be any problem with setting it and use it lot later

**Comment by strifel** [comment]
Since 8a06a782c363c0c061ed9ea8359a0ef6ef298cb1 there is now a config option.
