### ISSUE TITLE
A fun thing when lighting up nether portal by wooden furnace

### ISSUE THREAD

**Issue by friendlyhj** [strifel/Mod_WoodenFurnace#9]
you never think of it,right? XD
the frequency the nether portal flashes is higher actually.
![FjthK1.gif](https://s2.ax1x.com/2019/01/12/FjthK1.gif)

**Comment by strifel** [comment]
I will try to fix. To prevent lighting the nether portal up in hardcore modpacks in early game

**Comment by strifel** [comment]
I finally got Time to fix this (c86042fd4b9c99f90656c72a486253953d432d5d).
**->** Obsidian can not burn now (by wooden furnace)!
